# Generated by Django 5.2.4 on 2025-07-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="filename",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="파일명"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="original_filename",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="원본파일명"
            ),
        ),
    ]
